Duplicated import
```
  Compiling nerf
error: Duplicate import
  ┌─ build/packages/nerf/src/nerf/websocket.gleam:3:8
  │
3 │ import gleam/result
  │        ^^^^^^^^^^^^ First imported here
  ·
6 │ import gleam/result
  │        ^^^^^^^^^^^^ Reimported here

result has been imported multiple times.
Names in a Gleam module must be unique so one will need to be renamed.
```

Removing the line fixes the issue.